FROM datadog/agent:7

# Automatically set by Render
ARG RENDER_SERVICE_NAME=datadog

ENV DD_AUTOCONFIG_FROM_ENVIRONMENT=false
ENV NON_LOCAL_TRAFFIC=true
ENV DD_LOGS_STDOUT=yes
ENV DD_APM_ENABLED=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_LOGS_ENABLED=true
ENV DD_DOGSTATSD_SOCKET=1
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
ENV DD_PROCESS_AGENT_ENABLED=true
ENV DD_USE_DOGSTATSD=FALSE
ENV DD_SITE=datadoghq.com
ENV DD_BIND_HOST=$RENDER_SERVICE_NAME
ENV DD_HOSTNAME=$RENDER_SERVICE_NAME
ENV DD_API_KEY=$DD_API_KEY
ENV DD_ENV=$DD_ENV
